### ISSUE TITLE
Using an Ansible INI file as inventory source is not supported

### ISSUE THREAD

**Issue by konstruktoid** [ansible/ansible-rulebook#241]
* ansible-rulebook version:
```
__version__ = '0.9.4'
b1098dab-ac28-4b68-b604-d4b7bcebc07c
```
* Python version: `Python 3.10.6`
* Operating System: `Ubuntu 22.04.1 LTS`

### Description

```
TASK [Gathering Facts] *********************************************************
fatal: [...]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ...: Name or service not known", "unreachable": true}
ok: [127.0.0.1]
```

### What I Did

```
~$ ansible-rulebook --verbose --inventory inventory --rulebook otx.yml
INFO:ansible_rulebook.app:Starting sources
INFO:ansible_rulebook.app:Starting rules
INFO:ansible_rulebook.engine:run_ruleset
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO:ansible_rulebook.engine:ruleset define: {"name": "otx events", "hosts": ["all"], "sources": [{"EventSource": {"name": "Match all messages", "source_name": "ansible.eda.otx", "source_args": {"count": "1"}, "source_filters": []}}], "rules": [{"Rule": {"name": "Send to playboox", "condition": {"AllCondition": [{"IsDefinedExpression": {"Event": "otx"}}]}, "action": {"Action": {"action": "run_playbook", "action_args": {"name": "otx_ufw.yml"}}}, "enabled": true}}]}
INFO:ansible_rulebook.engine:load source
INFO:ansible_rulebook.engine:load source filters
INFO:ansible_rulebook.engine:Calling main in ansible.eda.otx
INFO:ansible_rulebook.engine:Waiting for event from otx events
INFO:ansible_rulebook.rule_generator:calling Send to playboox
INFO:ansible_rulebook.engine:call_action run_playbook
INFO:ansible_rulebook.engine:substitute_variables [{'name': 'otx_ufw.yml'}] [{'event': {'otx': {'ip': '193.105.210.113'}}, 'fact': {'otx': {'ip': '193.105.210.113'}}}]
INFO:ansible_rulebook.engine:action args: {'name': 'otx_ufw.yml'}
INFO:ansible_rulebook.builtin:running Ansible playbook: otx_ufw.yml
INFO:ansible_rulebook.builtin:ruleset: otx events, rule: Send to playboox
INFO:ansible_rulebook.builtin:Calling Ansible runner

PLAY [otx events] **************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [...]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: Could not resolve hostname ...: Name or service not known", "unreachable": true}
ok: [127.0.0.1]

TASK [debug msg] ***************************************************************
ok: [127.0.0.1] => {
    "msg": "debug task: 193.105.210.113"
}

PLAY RECAP *********************************************************************
...                        : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
127.0.0.1                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
^C
```

```
~$ ansible-inventory -i inventory --list
{
    "_meta": {
        "hostvars": {
            "127.0.0.1": {
                "ansible_connection": "local"
            }
        }
    },
    "all": {
        "children": [
            "ungrouped"
        ]
    },
    "ungrouped": {
        "hosts": [
            "127.0.0.1"
        ]
    }
}
```

```
~$ cat otx*.yml
---
- name: otx events
  hosts: all
  sources:
    - name: Match all messages
      ansible.eda.otx:
        count: "1"
  rules:
    - name: Send to playboox
      condition: event.otx is defined
      action:
        run_playbook:
          name: otx_ufw.yml
...
---
- name: otx events
  hosts: all
  tasks:
    - name: debug msg
      ansible.builtin.debug:
        msg: "debug task: {{ event.otx.ip }}"
...
```

**Comment by konstruktoid** [comment]
the code used is available at https://github.com/konstruktoid/ansible-event-otx

**Comment by Alex-Izquierdo** [comment]
Hello @konstruktoid. 
Thanks for the report. I was not able to reproduce the problem. I would need more info. 
First, if you can confirm is the version installed from pip, otherwise the specific commit of `ansible-rulebook` that you are using. 
As we are not working with pinned versions for dependencies yet, I would need the output of the `pip freeze` cmd as well as the version of the JVM. 

Also please, use the `--debug` flag in addition to the `--verbose` flag

Does the problem happen if your inventory contains `localhost` instead `127.0.0.1` as host? 

Tip: There is no need to move your custom source plugin into eda collection, you can load it from any place with the `-S` flag.

**Comment by konstruktoid** [comment]
I will retest, but the `ansible-rulebook` version was `__version__ = '0.9.4' b1098dab-ac28-4b68-b604-d4b7bcebc07c`.

**Comment by Alex-Izquierdo** [comment]
> I will retest, but the `ansible-rulebook` version was `__version__ = '0.9.4' b1098dab-ac28-4b68-b604-d4b7bcebc07c`.

The uuid after the version has no meaning and it will be removed. The only thing is if you are using the package from pypi or it was installed from the source code.

**Comment by konstruktoid** [comment]
https://github.com/konstruktoid/ansible-event-otx/blob/main/Vagrantfile#L1-L15 and then `git clone https://github.com/ansible/event-driven-ansible.git` but I'll update the script to print the versions

**Comment by konstruktoid** [comment]
```sh
vagrant@ubuntu:~/event-driven-ansible$ ansible-rulebook --version
__version__ = '0.9.4'
14502b13-8f73-4bf5-a620-ba86e1a0db8d
vagrant@ubuntu:~/event-driven-ansible$ ansible-galaxy collection list | grep 'ansible.eda'
ansible.eda 1.3.3
vagrant@ubuntu:~/event-driven-ansible$ git log -n1
commit 8d1d381e07459264dfb951c79a943aba3118e634 (HEAD -> main, origin/main, origin/HEAD)
Merge: 2fb9611 2eccd9d
Author: Doug Donahue <57504257+ddonahue007@users.noreply.github.com>
Date:   Tue Nov 29 08:49:45 2022 -0500

    Merge pull request #52 from ansible/ttuffin/AAP-6828_installer_tests

    Add Github workflow tests for ansible-rulebook installer
vagrant@ubuntu:~$ cd ..
vagrant@ubuntu:~$ cat inventory
127.0.0.1 ansible_connection=local
vagrant@ubuntu:~$ ansible-rulebook --inventory inventory --rulebook otx.yml -S /vagrant/otx.py
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR:ansible_rulebook.engine:Source error
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.10/site-packages/ansible_rulebook/engine.py", line 94, in start_source
    raise Exception(
Exception: Could not find source plugin for ansible.eda.otx
vagrant@ubuntu:~$ ansible-rulebook --inventory inventory --rulebook otx.yml -S /vagrant/
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR:ansible_rulebook.engine:Source error
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.10/site-packages/ansible_rulebook/engine.py", line 94, in start_source
    raise Exception(
Exception: Could not find source plugin for ansible.eda.otx
```

**Comment by konstruktoid** [comment]
```sh
vagrant@ubuntu:~$ ansible-rulebook --inventory inventory --rulebook otx.yml -S /vagrant/sources/
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ERROR:ansible_rulebook.engine:Source error
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.10/site-packages/ansible_rulebook/engine.py", line 94, in start_source
    raise Exception(
Exception: Could not find source plugin for ansible.eda.otx
```

**Comment by Alex-Izquierdo** [comment]
@konstruktoid If you use the `-S` flag, you must define the source plugin in the right collection space, which in your case would call it directly as:
```
  sources:
    - name: Match all messages
      otx:
        count: "1"
```

**Comment by Alex-Izquierdo** [comment]
The reason of your problem is because the inventory is in INI format, which is not fully supported yet by ansible-rulebook. As a workaround you can use a yaml format.

**Comment by konstruktoid** [comment]
> @konstruktoid If you use the `-S` flag, you must define the source plugin in the right collection space, which in your case would call it directly as:
> 
> ```
>   sources:
>     - name: Match all messages
>       otx:
>         count: "1"
> ```

Where is all this documented?

```sh
vagrant@ubuntu:~$ ansible-rulebook --verbose --inventory inventory --rulebook /vagrant/otx.yml -S /vagrant/sources/
INFO:ansible_rulebook.app:Starting sources
INFO:ansible_rulebook.app:Starting rules
INFO:ansible_rulebook.engine:run_ruleset
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
INFO:ansible_rulebook.engine:ruleset define: {"name": "otx events", "hosts": ["all"], "sources": [{"EventSource": {"name": "Match all messages", "source_name": "otx", "source_args": {"count": "1"}, "source_filters": []}}], "rules": [{"Rule": {"name": "Send to playboox", "condition": {"AllCondition": [{"IsDefinedExpression": {"Event": "otx"}}]}, "action": {"Action": {"action": "run_playbook", "action_args": {"name": "otx_ufw.yml"}}}, "enabled": true}}]}
INFO:ansible_rulebook.engine:load source
ERROR:ansible_rulebook.engine:Source error
Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.10/site-packages/ansible_rulebook/engine.py", line 94, in start_source
    raise Exception(
Exception: Could not find source plugin for otx
INFO:ansible_rulebook.engine:Waiting for event from otx events
INFO:ansible_rulebook.engine:Canceling all ruleset tasks
INFO:ansible_rulebook.app:Cancelling event source tasks
INFO:ansible_rulebook.app:Main complete
vagrant@ubuntu:~$ cat /vagrant/otx.yml 
---
- name: otx events
  hosts: all
  sources:
    - name: Match all messages
      otx:
        count: "1"
  rules:
    - name: Send to playboox
      condition: event.otx is defined
      action:
        run_playbook:
          name: otx_ufw.yml
```

**Comment by konstruktoid** [comment]
> The reason of your problem is because the inventory is in INI format, which is not fully supported yet by ansible-rulebook. As a workaround you can use a yaml format.

yeah, this was the issue. Using yaml format it worked.

**Comment by AlexonOliveiraRH** [comment]
@Alex-Izquierdo, as you saw in my duplicated [Issue #86](https://github.com/ansible/event-driven-ansible/issues/86), I'm facing the same problem as @konstruktoid:

```
$ ansible-rulebook --rulebook rulebook.yaml -i ./inventory.ini 
2023-03-03 17:25:46,595 - ansible_rulebook.cli - ERROR - Unexpected exception
Traceback (most recent call last):
  File "/home/localuser/.local/lib/python3.10/site-packages/ansible_rulebook/cli.py", line 203, in main
    asyncio.run(app.run(args))
  File "/usr/lib64/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/localuser/.local/lib/python3.10/site-packages/ansible_rulebook/app.py", line 67, in run
    inventory = load_inventory(parsed_args.inventory)
  File "/home/localuser/.local/lib/python3.10/site-packages/ansible_rulebook/util.py", line 70, in load_inventory
    inventory_data = yaml.safe_load(f.read())
  File "/usr/lib64/python3.10/site-packages/yaml/__init__.py", line 125, in safe_load
    return load(stream, SafeLoader)
  File "/usr/lib64/python3.10/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
  File "/usr/lib64/python3.10/site-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "/usr/lib64/python3.10/site-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/lib64/python3.10/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/lib64/python3.10/site-packages/yaml/parser.py", line 171, in parse_document_start
    raise ParserError(None, None,
yaml.parser.ParserError: expected '<document start>', but found '<scalar>'
  in "<unicode string>", line 2, column 1:
    fedora.example.local
    ^
```

Is there any prediction on when this is going to be supported or if it's going to be supported at all?
